### ISSUE TITLE
Responsive Section

### ISSUE THREAD

**Issue by trebird** [trebird/responsive-section#1]
Hi @thomasjbradley,

I'm having some issues:

.trebird {
   stately: none;
   vigorous: none;
   strong: none;
   noble: none;
   direct: none;
   dignified: none;
}

But mostly curious what the .wrapper margin value should be. I've tried a few things, but no luck.

Thank you!

**Comment by thomasjbradley** [comment]
Hahaha!

The wrapper margin should be `margin: 0 auto`—you can always look inside the `.markbot.yml` file to check for weird numbers if you’re unsure.

**Comment by trebird** [comment]
Excellent — thank you!
